on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v4
      - name: compile
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            apk add make
            make -k
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: tesi-zaninotto
          path: out/thesis.pdf
